<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\EventViewEmbeddedController
 */
class EventViewEmbeddedControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function show_embedded_event_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $event = factory(\App\Models\Event::class)->create();

        $response = $this->get(route('showEmbeddedEventPage', ['event_id' => $event_id]));

        $response->assertOk();
        $response->assertViewIs('Public.ViewEvent.Embedded.EventPage');

        // TODO: perform additional assertions
    }

    // test cases...
}
