<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\EventWidgetsController
 */
class EventWidgetsControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function show_event_widgets_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $event = factory(\App\Models\Event::class)->create();
        $user = factory(\App\Models\User::class)->create();

        $response = $this->actingAs($user)->get(route('showEventWidgets', ['event_id' => $event_id]));

        $response->assertOk();
        $response->assertViewIs('ManageEvent.Widgets');

        // TODO: perform additional assertions
    }

    // test cases...
}
