<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\OrganiserEventsController
 */
class OrganiserEventsControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function show_events_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $events = factory(\App\Models\Event::class, 3)->create();
        $user = factory(\App\Models\User::class)->create();

        $response = $this->actingAs($user)->get(route('showOrganiserEvents', ['organiser_id' => $organiser_id]));

        $response->assertOk();
        $response->assertViewIs('ManageOrganiser.Events');

        // TODO: perform additional assertions
    }

    // test cases...
}
