<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\OrganiserCustomizeController
 */
class OrganiserCustomizeControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function post_edit_organiser_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $organiser = factory(\App\Models\Organiser::class)->create();
        $user = factory(\App\Models\User::class)->create();

        $response = $this->actingAs($user)->post(route('postEditOrganiser', ['organiser_id' => $organiser_id]), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function post_edit_organiser_page_design_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $organiser = factory(\App\Models\Organiser::class)->create();
        $user = factory(\App\Models\User::class)->create();

        $response = $this->actingAs($user)->post(route('postEditOrganiserPageDesign', ['organiser_id' => $organiser_id]), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_customize_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $organiser = factory(\App\Models\Organiser::class)->create();
        $user = factory(\App\Models\User::class)->create();

        $response = $this->actingAs($user)->get(route('showOrganiserCustomize', ['organiser_id' => $organiser_id]));

        $response->assertOk();
        $response->assertViewIs('ManageOrganiser.Customize');

        // TODO: perform additional assertions
    }

    // test cases...
}
