<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\IndexController
 */
class IndexControllerTest extends TestCase
{
    /**
     * @test
     */
    public function show_index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('index'));

        $response->assertRedirect(route('showSelectOrganiser'));

        // TODO: perform additional assertions
    }

    // test cases...
}
