<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\UserLoginController
 */
class UserLoginControllerTest extends TestCase
{
    /**
     * @test
     */
    public function post_login_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post('login', [
            // TODO: send request data
        ]);

        $response->assertRedirect(intended(route('showSelectOrganiser')));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_login_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('login'));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
